### ISSUE TITLE
Laravel Passport Error - ServerException in RequestException.php line 107:

### ISSUE THREAD

**Issue by HassanMahmoudd** [laravel/passport#109]
Hello,

Need some help, please.

I followed the tutorial What's New in Laravel 5.3: Laravel Passport (https://laracasts.com/series/whats-new-in-laravel-5-3/episodes/13) step by step and i have this error:

ServerException in RequestException.php line 107: Server error: POST http://latest.dev/oauth/token resulted in a 500 Internal Server Error response: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'consumer.oauth_clients' doesn't exist (SQL: select * from `oa (truncated...)
![passport issue 1](https://cloud.githubusercontent.com/assets/17252153/18846671/61a49f44-8427-11e6-90a6-1f89f5068d7e.png)

latest.dev

![passport issue 2](https://cloud.githubusercontent.com/assets/17252153/18846700/81272814-8427-11e6-8c29-b5e5720180ca.png)

consumer.dev

![passport issue 3](https://cloud.githubusercontent.com/assets/17252153/18846715/9426dff4-8427-11e6-8414-d0aa3dc2821e.png)

**Comment by craigpaul** [comment]
The error is right there in the stacktrace.

```
Base table or view not found: 1146 Table 'consumer.oauth_clients'
```

That mean's your `latest.dev` project either has a bad database connection, or you never ran the migrations in that project. Could you double check those things and then hopefully we can figure out your problem.

**Comment by HassanMahmoudd** [comment]
I made sure that latest.dev project has the required migrations & specifically oauth_clients table .. But the error says that it looks for oauth_clients table in consumer.dev & not latest.dev which is unlogical I think

**Comment by craigpaul** [comment]
I'll set up a 2 projects and see if I can replicate it, but in the mean time, why is `client_secret` empty in your `/callback` route?

**Comment by HassanMahmoudd** [comment]
Sorry the photo is a little old but client_secret was already fixed before & still there is an error :(
![passport issue 4](https://cloud.githubusercontent.com/assets/17252153/18848125/4898b62e-842d-11e6-9583-b3f71c68710d.png)

**Comment by craigpaul** [comment]
Hey @HassanMahmoudd,

So I went through the video and followed along like you said you had done, but no errors occurred. What versions are you using for Passport and Laravel? All your code shown seems to be correct to me, which leads me to believe it's a configuration error. 

Perhaps you can post the entire stack trace and that might have some clues? Also if you could, post the `DB_*` env variables from both projects.

**Comment by HassanMahmoudd** [comment]
Here are latest.dev DB_* variables
![passport issue 5](https://cloud.githubusercontent.com/assets/17252153/18849225/3cb23876-8432-11e6-9929-53d413a1f544.png)
Here are consumer.dev DB_* variables
![passport issue 6](https://cloud.githubusercontent.com/assets/17252153/18849249/569d3a2e-8432-11e6-8a37-fe3a46b10a06.png)
- It will be very helpful & thankful if you push your both projects on github so that I can check what's wrong with mine or send them to my email "hassanmahmoudsd@gmail.com"
- Thanks a lot for your effort :)

**Comment by craigpaul** [comment]
No problem, hopefully you can find out what you did wrong. Also, it's very weird to me that the error was with a database called `consumer` but yet your `DB_DATABASE` for consumer is called `testconsumer`. Hmm... either way, here are the repo's @HassanMahmoudd 

https://github.com/craigpaul/provider
https://github.com/craigpaul/consumer

**Comment by danielistyo** [comment]
Hei @HassanMahmoudd, are your problem solve ? I also have problem like you

**Comment by HassanMahmoudd** [comment]
@craigpaul I tried to drop the "consumer" database & make a new one called "testconsumer" that's why they are different but the problem isn't there & I also pulled your both projects & tested them but the same error happened again .. @danielistyo No the problem is still there

**Comment by danielistyo** [comment]
@HassanMahmoudd, Okay thanks. I solve my problem using 2 laptops. I separate server and consumer in difference laptops.

**Comment by HassanMahmoudd** [comment]
@danielistyo Thanks a lot you are right now problem is solved .. Also the server and the consumer can be on the same computer but they must access different ports for example the server is on localhost:9000 & the consumer is on localhost:9999 ..  I tried that & It worked

**Comment by craigpaul** [comment]
@HassanMahmoudd, ah, didn't realize you were using that kind of setup. I assumed it was inside a VM. Either way, if you've got it all fixed up, could you close the issue? Thanks!!

**Comment by zohaib055** [comment]
Hi this is not a big issue just to implement it on server you must

Run the following command

php artisan serve

and replace the paths passport.dev to http://127.0.0.1:8000

and try again then it will work

**Comment by bogem25** [comment]
> @danielistyo Thanks a lot you are right now problem is solved .. Also the server and the consumer can be on the same computer but they must access different ports for example the server is on localhost:9000 & the consumer is on localhost:9999 .. I tried that & It worked

Hai @HassanMahmoudd , I faced same problem here. I could solve if I run php artisan serve like @zohaib055 . Later I tried with your solve by configuring my XAMPP (Apache vhost with different port), however the problem persists although I'm using different port like you said. Does it need to be configured more specific in Apache config maybe ? 
Anyway I don't try yet the @danielistyo solution (Need buy more laptop 😄 )

Need your advise guys
Thanks

**Comment by ajcarrillo** [comment]
I have the some error but only in windows, in my osx run perfectly. Did you find the solution for this?

**Comment by raulfdias** [comment]
> I have the some error but only in windows, in my osx run perfectly. Did you find the solution for this?

Hi guys. 
I had the same problem, but when I copied the database settings that were in `.env` to `config/database.php` and ran the `php artisan config:cache` command it worked. I am using two applications on the same notebook, one on port 7305 and one on port 7309 using windows and xampp.

**Comment by vijaykanaujia** [comment]
@raulfdias  thank you it's also work for me
